name: 功能操作
description: 用于处理新功能、需要重构、文档补充、样式、杂项、其他部分的填写
title: "[feat] <please input>"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## 提交注意
        
        请在右侧部分选择受理人为 **XiaoLFeng**，并填写进入相对应的标签。
        
        ## 标题要求
        
        - 若您之前发布了 Issue 或者为了修复 Issue 而提交了合并请求，请在标题中填写对应的 Issue 编号，例如：[#1] 修复用户登陆功能
        - 若您未提交 Issue 或者为了新功能而提交了合并请求，请在标题中填写新功能的内容，例如：
          - [feat] 完成用户登陆功能
          - [docs] 完善用户登陆功能文档
        
        ---
  - type: dropdown
    id: issue-dropdown-1
    attributes:
      label: 类型(type)
      description: 请选择此工单的类型(The type of this issue)
      options:
        - 新功能(feat)
        - 重构(refactor)
        - 文档(docs)
        - 样式(style)
        - 测试(test)
        - 杂项(chore)
        - 其他(other)
        - 未知(unknown)
    validations:
      required: true
  - type: textarea
    id: issue-textarea-1
    attributes:
      label: 简要描述(Description)
      description: 请简要描述此工单的内容(Briefly describe the content of this issue)
      placeholder: 完成用户登陆功能，修复用户登陆功能等。(complete user login function, fix user login function, etc.)
    validations:
      required: true