name: 漏洞(bug)
description: 用于处理漏洞修复的填写(Used to handle the filling of bug fixes)
title: "[bug] <please input>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## 提交注意
        
        请在右侧部分选择受理人为 **XiaoLFeng**，并填写进入相对应的标签。
        
        ## 标题要求
        
        请按照以下格式填写标题：
        - [bug] 需要修复用户登陆功能
        - [bug] need to fix user login function
        ---
  - type: textarea
    id: issue-textarea-1
    attributes:
      label: 漏洞说明(Description)
      description: 请简要描述此工单的内容(Briefly describe the content of this issue)
      placeholder: 用户登陆出现可渗透漏洞。(User login has a penetrable vulnerability.)
    validations:
      required: true